package com.honeywell.android.data.generate;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.honeywell.android.data.model.InventoryItem;
import com.honeywell.android.data.model.InventoryTask;
import com.honeywell.android.data.model.User;

import com.honeywell.android.data.generate.InventoryItemDao;
import com.honeywell.android.data.generate.InventoryTaskDao;
import com.honeywell.android.data.generate.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig inventoryItemDaoConfig;
    private final DaoConfig inventoryTaskDaoConfig;
    private final DaoConfig userDaoConfig;

    private final InventoryItemDao inventoryItemDao;
    private final InventoryTaskDao inventoryTaskDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        inventoryItemDaoConfig = daoConfigMap.get(InventoryItemDao.class).clone();
        inventoryItemDaoConfig.initIdentityScope(type);

        inventoryTaskDaoConfig = daoConfigMap.get(InventoryTaskDao.class).clone();
        inventoryTaskDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        inventoryItemDao = new InventoryItemDao(inventoryItemDaoConfig, this);
        inventoryTaskDao = new InventoryTaskDao(inventoryTaskDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(InventoryItem.class, inventoryItemDao);
        registerDao(InventoryTask.class, inventoryTaskDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        inventoryItemDaoConfig.clearIdentityScope();
        inventoryTaskDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public InventoryItemDao getInventoryItemDao() {
        return inventoryItemDao;
    }

    public InventoryTaskDao getInventoryTaskDao() {
        return inventoryTaskDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
